name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-latest:
    name: Unit Test - iOS 15.2, Xcode 13.2
    runs-on: macOS-11
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test -d "OS=15.2,name=iPhone 13 Pro"
        